### ISSUE TITLE
RX Module Not found

### ISSUE THREAD

**Issue by michaelryancaputo** [normative/generator-hapi-service#18]
/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:4586
	        throw e;
	              ^
	TypeError: undefined is not a function
	    at run (/usr/local/lib/node_modules/generator-hapi-service/node_modules/yeoman-generator/lib/base.js:444:21)
	    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:331:20)
	    at module.exports (/usr/local/lib/node_modules/yo/lib/routes/run.js:20:11)
	    at Router.navigate (/usr/local/lib/node_modules/yo/lib/router.js:36:30)
	    at PromptUI.completed (/usr/local/lib/node_modules/yo/lib/routes/home.js:76:20)
	    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:69:10)
	    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1929:12)
	    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)
	    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:4604:23)
	    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)

**Comment by michaelryancaputo** [comment]
Had to update my npm packages to get this to work...
